version: '3.8'
services:
  redis:
    image: redis:7.0
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
    networks:
      - app-network

  redis_worker:
    image: redis:7.0
    networks:
      - app-network
    deploy:
      replicas: 2
  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=1234
    networks:
      - app-network

  redis-exporter:
    image: oliver006/redis_exporter:latest
    ports:
      - "9121:9121"
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - app-network

  mongodb-exporter:
    image: percona/mongodb_exporter:0.40
    ports:
      - "9216:9216"
    environment:
      - MONGODB_URI=mongodb://admin:your_password@mongodb:27017
    networks:
      - app-network

  prometheus:
    image: prom/prometheus:v2.47.0
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    networks:
      - app-network

  grafana:
    image: grafana/grafana:10.1.0
    ports:
      - "3000:3000"
    volumes:
      - grafana-data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=your_grafana_password
    networks:
      - app-network

volumes:
  redis-data:
  mongo-data:
  prometheus-data:
  grafana-data:

networks:
  app-network:
    driver: bridge